site_name: Documentation
docs_dir: docs
theme:
  locale: en
  logo: whitelogo.png
  favicon: whitelogo.png
  language: en
  name: material
  icon:
    repo: fontawesome/brands/github
  font: 
    text: Roboto Condensed
  palette:
    primary: green
    accent: green
  features:
    - content.code.copy
    - content.code.annotate
repo_name: immosheets
repo_url: https://github.com/arthuRHD/immosheets
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
copyright: Arthur RICHARD @2023